
[color]
draw_bold_text_with_bright_colors = true
cursor = { text = "0x44475a", cursor = "0xf8f8f2" }

[font]
size = 12.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "italic" }

[window]
opacity = 0.7
blur = true
dynamic_padding = true
padding = { x = 5, y = 5 }
dimensions = { columns = 120, lines = 50 }
decorations = "none"

[selection]
save_to_clipboard = true


[key]
bindings = [
   { key = "V", mods = "Control", action = "Paste" },
   { key = "C", mods = "Control", action = "Copy" },
   { key = "A", mods = "Command", chars = "\\x01" },
   { key = "B", mods = "Command", chars = "\\x02" },
   { key = "C", mods = "Command", chars = "\\x03" },
   { key = "D", mods = "Command", chars = "\\x04" },
   { key = "E", mods = "Command", chars = "\\x05" },
   { key = "F", mods = "Command", chars = "\\x06" },
   { key = "G", mods = "Command", chars = "\\x07" },
   { key = "H", mods = "Command", chars = "\\x08" },
   { key = "I", mods = "Command", chars = "\\x09" },
   { key = "J", mods = "Command", chars = "\\x0A" },
   { key = "K", mods = "Command", chars = "\\x0B" },
   { key = "L", mods = "Command", chars = "\\x0C" },
   { key = "M", mods = "Command", chars = "\\x0D" },
   { key = "N", mods = "Command", chars = "\\x0E" },
   { key = "O", mods = "Command", chars = "\\x0F" },
   { key = "P", mods = "Command", chars = "\\x10" },
   { key = "Q", mods = "Command", chars = "\\x11" },
   { key = "R", mods = "Command", chars = "\\x12" },
   { key = "S", mods = "Command", chars = "\\x13" },
   { key = "T", mods = "Command", chars = "\\x14" },
   { key = "U", mods = "Command", chars = "\\x15" },
   { key = "V", mods = "Command", chars = "\\x16" },
   { key = "W", mods = "Command", chars = "\\x17" },
   { key = "X", mods = "Command", chars = "\\x18" },
   { key = "Y", mods = "Command", chars = "\\x19" },
   { key = "Z", mods = "Command", chars = "\\x1A" },
   { key = "Key1", mods = "Command", chars = "\\x1bOP" },
   { key = "Key2", mods = "Command", chars = "\\x1bOQ" },
   { key = "Key3", mods = "Command", chars = "\\x1bOR" },
   { key = "Key4", mods = "Command", chars = "\\x1bOS" },
   { key = "Key5", mods = "Command", chars = "\\x1b[15~" },
   { key = "Key6", mods = "Command", chars = "\\x1b[17~" },
   { key = "Key7", mods = "Command", chars = "\\x1b[18~" },
   { key = "Key8", mods = "Command", chars = "\\x1b[19~" },
   { key = "Key9", mods = "Command", chars = "\\x1b[20~" },
   { key = "Key0", mods = "Command", chars = "\\x1b[21~" },
   # Fix Alt as Meta in macOS
   { key = "A", mods = "Option", chars = "\\x1Ba" },
   { key = "B", mods = "Option", chars = "\\x1Bb" },
   { key = "C", mods = "Option", chars = "\\x1Bc" },
   { key = "D", mods = "Option", chars = "\\x1Bd" },
   { key = "E", mods = "Option", chars = "\\x1Be" },
   { key = "F", mods = "Option", chars = "\\x1Bf" },
   { key = "G", mods = "Option", chars = "\\x1Bg" },
   { key = "H", mods = "Option", chars = "\\x1Bh" },
   { key = "I", mods = "Option", chars = "\\x1Bi" },
   { key = "J", mods = "Option", chars = "\\x1Bj" },
   { key = "K", mods = "Option", chars = "\\x1Bk" },
   { key = "L", mods = "Option", chars = "\\x1Bl" },
   { key = "M", mods = "Option", chars = "\\x1Bm" },
   { key = "N", mods = "Option", chars = "\\x1Bn" },
   { key = "O", mods = "Option", chars = "\\x1Bo" },
   { key = "P", mods = "Option", chars = "\\x1Bp" },
   { key = "Q", mods = "Option", chars = "\\x1Bq" },
   { key = "R", mods = "Option", chars = "\\x1Br" },
   { key = "S", mods = "Option", chars = "\\x1Bs" },
   { key = "T", mods = "Option", chars = "\\x1Bt" },
   { key = "U", mods = "Option", chars = "\\x1Bu" },
   { key = "V", mods = "Option", chars = "\\x1Bv" },
   { key = "W", mods = "Option", chars = "\\x1Bw" },
   { key = "X", mods = "Option", chars = "\\x1Bx" },
   { key = "Y", mods = "Option", chars = "\\x1By" },
   { key = "Z", mods = "Option", chars = "\\x1Bz" },
   { key = "A", mods = "Option|Shift", chars = "\\x1BA" },
   { key = "B", mods = "Option|Shift", chars = "\\x1BB" },
   { key = "C", mods = "Option|Shift", chars = "\\x1BC" },
   { key = "D", mods = "Option|Shift", chars = "\\x1BD" },
   { key = "E", mods = "Option|Shift", chars = "\\x1BE" },
   { key = "F", mods = "Option|Shift", chars = "\\x1BF" },
   { key = "G", mods = "Option|Shift", chars = "\\x1BG" },
   { key = "H", mods = "Option|Shift", chars = "\\x1BH" },
   { key = "I", mods = "Option|Shift", chars = "\\x1BI" },
   { key = "J", mods = "Option|Shift", chars = "\\x1BJ" },
   { key = "K", mods = "Option|Shift", chars = "\\x1BK" },
   { key = "L", mods = "Option|Shift", chars = "\\x1BL" },
   { key = "M", mods = "Option|Shift", chars = "\\x1BM" },
   { key = "N", mods = "Option|Shift", chars = "\\x1BN" },
   { key = "O", mods = "Option|Shift", chars = "\\x1BO" },
   { key = "P", mods = "Option|Shift", chars = "\\x1BP" },
   { key = "Q", mods = "Option|Shift", chars = "\\x1BQ" },
   { key = "R", mods = "Option|Shift", chars = "\\x1BR" },
   { key = "S", mods = "Option|Shift", chars = "\\x1BS" },
   { key = "T", mods = "Option|Shift", chars = "\\x1BT" },
   { key = "U", mods = "Option|Shift", chars = "\\x1BU" },
   { key = "V", mods = "Option|Shift", chars = "\\x1BV" },
   { key = "W", mods = "Option|Shift", chars = "\\x1BW" },
   { key = "X", mods = "Option|Shift", chars = "\\x1BX" },
   { key = "Y", mods = "Option|Shift", chars = "\\x1BY" },
   { key = "Z", mods = "Option|Shift", chars = "\\x1BZ" },
   { key = "Key1", mods = "Option", chars = "\\x1B1" },
   { key = "Key2", mods = "Option", chars = "\\x1B2" },
   { key = "Key3", mods = "Option", chars = "\\x1B3" },
   { key = "Key4", mods = "Option", chars = "\\x1B4" },
   { key = "Key5", mods = "Option", chars = "\\x1B5" },
   { key = "Key6", mods = "Option", chars = "\\x1B6" },
   { key = "Key7", mods = "Option", chars = "\\x1B7" },
   { key = "Key8", mods = "Option", chars = "\\x1B8" },
   { key = "Key9", mods = "Option", chars = "\\x1B9" },
   { key = "Key0", mods = "Option", chars = "\\x1B0" },
   { key = "Space", mods = "Control", chars = "\\x1B" },
   { key = "Grave", mods = "Option", chars = "\\x1B`" },
   { key = "Grave", mods = "Option|Shift", chars = "\\x1B~" },
   { key = "Period", mods = "Option", chars = "\\x1B." },
   { key = "Key8", mods = "Option|Shift", chars = "\\x1B*" },
   { key = "Key3", mods = "Option|Shift", chars = "\\x1B#" },
   { key = "Period", mods = "Option|Shift", chars = "\\x1B>" },
   { key = "Comma", mods = "Option|Shift", chars = "\\x1B<" },
   { key = "Minus", mods = "Option|Shift", chars = "\\x1B_" },
   { key = "Key5", mods = "Option|Shift", chars = "\\x1B%" },
   { key = "Key6", mods = "Option|Shift", chars = "\\x1B^" },
   { key = "Backslash", mods = "Option", chars = "\\x1B\\" },
   { key = "Backslash", mods = "Option|Shift", chars = "\\x1B|" },
   { key = "Paste", action = "Paste" },
   { key = "Copy", action = "Copy" },
]
