
theme = "boo_berry"

[keys.normal]
"C-s" = ":write"
F1 = ":config-open"
g = { a = "code_action" }
"C-/" = "toggle_comments"
"C-r" = ":reload"
"\\" = ":reflow" # |
a = ["move_char_right", "insert_mode"]
 
[keys.insert]
j = { j = "normal_mode" }


[editor]
true-color = true
line-number = "relative"
mouse = true
scrolloff = 8
cursorline = true

[editor.cursor-shape]
normal="block"
insert="bar"
select="block"


[editor.indent-guides]
render = true
character = "│"

[editor.lsp]
display-messages = true


[editor.statusline]
left = ["mode", "spinner", "version-control", "spacer", "file-name"]
center = ["diagnostics"]
right = ["position", "selections", "file-encoding", "file-type", "separator"]

separator = ""

mode.normal = ' '
mode.insert = '  '
mode.select = ' '
