
theme = "tokyonight_storm"

[keys.normal]
C-s = ":w"
C-o = ":open ~/AppData/Roaming/helix/config.toml"
g = { a = "code_action" }


[keys.insert]
j = { j = "normal_mode" }


[editor]
line-number = "relative"
mouse = true
scrolloff = 8
cursorline = true

[editor.cursor-shape]
normal="block"
insert="bar"
select="block"


[editor.indent-guides]
render = true
character = "|"


[editor.statusline]
left = ["mode", "spinner", "separator", 'spacer', 'file-name']
center = ["diagnostics"]
right = ["position", "selections", "file-encoding", "file-type"]
