theme = "noctis"
# theme = "naysayer"
# theme = "base16_transparent"
# theme = "boo_berry"
# theme = "tokyonight"

[keys.normal]
"C-s" = ":write"
"F1" = ":config-open"
g = { a = "code_action" }
"C-r" = ":reload"
"\\" = ":reflow" # |
a = ["move_char_right", "insert_mode"]
H = ["goto_line_start"]
L = ["goto_line_end"]
"C-y" = [
  ':sh del %TEMP%\unique-file',
  ':insert-output yazi.exe %{buffer_name} --chooser-file=%TEMP%\unique-file',
  ':open %sh{type %TEMP%\unique-file}',
  ':redraw',
]

 
[keys.insert]
j = { j = "normal_mode" }


[editor]
true-color = true
line-number = "relative"
mouse = true
scrolloff = 8
cursorline = true
# shell = ["powershell", "/c"]
bufferline = "multiple"
continue-comments = true
auto-completion = true
path-completion = true
auto-format = true
auto-pairs = true
idle-timeout = 300
completion-timeout = 300
completion-replace = true
color-modes = true
popup-border = "all"
end-of-line-diagnostics = "hint"


[editor.inline-diagnostics]
cursor-line = "hint"


[editor.cursor-shape]
normal="block"
insert="bar"
select="block"


[editor.indent-guides]
render = true
character = "│"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
snippets = true 
display-inlay-hints = true
goto-reference-include-declaration = true


[editor.statusline]
left = ["mode", "spinner", "version-control", "spacer", "file-name"]
center = ["diagnostics"]
right = ["position", "selections", "file-encoding", "file-type", "separator"]

separator = ""

mode.normal = ' '
mode.insert = '  '
mode.select = ' '
